name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Configure git
        run: |
          git config --global user.email "soumya.jindal07@gmail.com"
          git config --global user.name "soumyajindal07"      
      - name: Pull latest changes
        run: git pull origin main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://SoumyaJ:$HF_TOKEN@huggingface.co/spaces/SoumyaJ/Restocking-Prediction main
